name: TELECHARGEMENT-BDD
on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

env:
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    MAIL: ${{ secrets.MAIL }}
    PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  TELECHARGEMENT-BDD:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Vérification des codes espèces
        run:  |
          ./SCRIPTS/CODES.ps1

      - name: Téléchargement des bases de données
        if: always()
        run:  |
          $params = @{client_id="$env:CLIENT_ID";grant_type='password';email="$env:MAIL";password="$env:PASSWORD"}
          ./SCRIPTS/TELECHARGEMENTS.ps1

      - name: Création des fichiers KML et GeoJSON
        if: success()
        run:  |
          ./SCRIPTS/KML.ps1
          ./SCRIPTS/GEOJSON.ps1
      
      - name: Création des cartes Cigales de France et de l'Europe
        if: success()
        run:  |
          choco install r.project pandoc --no-progress -y
          Rscript ./SCRIPTS/CARTES-CDF.R
          Rscript ./SCRIPTS/CARTES-EUROPE.R
          ./SCRIPTS/FIN.ps1
