name: TELECHARGEMENT-BDD
on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  TELECHARGEMENT-BDD:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2-branch

      - name: Création des cartes de l'Europe
        if: always()
        run:  |
          choco install pandoc -y
          Rscript ./SCRIPTS/CARTES-EUROPE.R

      - name: Téléchargement des bases de données et construction des kml
        if: always()
        run:  |
          ./SCRIPTS/BDD.ps1
